on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install datadog-checks-base
        run: pip install datadog-checks-base[deps]

      - name: Run test
        run: python3 -m unittest tests/test_grpc_check.py
